apiVersion: v1
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        deployment.kubernetes.io/revision: "1"
      creationTimestamp: "2021-08-25T17:57:14Z"
      generation: 1
      labels:
        app: currency-conversion
      name: currency-conversion
      namespace: default
      resourceVersion: "9646"
      uid: ebf888fc-7646-4635-9c6f-522cc4f83fa8
    spec:
      progressDeadlineSeconds: 600
      replicas: 2
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          app: currency-conversion
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: currency-conversion
        spec:
          containers:
            - image: ezazulhaq02/currency-conversion-service:0.0.2-SNAPSHOT
              imagePullPolicy: IfNotPresent
              name: currency-conversion-service
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
    status:
      availableReplicas: 1
      conditions:
        - lastTransitionTime: "2021-08-25T17:57:28Z"
          lastUpdateTime: "2021-08-25T17:57:28Z"
          message: Deployment has minimum availability.
          reason: MinimumReplicasAvailable
          status: "True"
          type: Available
        - lastTransitionTime: "2021-08-25T17:57:14Z"
          lastUpdateTime: "2021-08-25T17:57:28Z"
          message: ReplicaSet "currency-conversion-545ccccd5" has successfully progressed.
          reason: NewReplicaSetAvailable
          status: "True"
          type: Progressing
      observedGeneration: 1
      readyReplicas: 1
      replicas: 1
      updatedReplicas: 1
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        deployment.kubernetes.io/revision: "1"
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2021-08-25T17:46:03Z","generation":1,"labels":{"app":"currency-exchange"},"name":"currency-exchange","namespace":"default","resourceVersion":"6290","uid":"e697957c-3664-49db-92a3-81c85625c045"},"spec":{"progressDeadlineSeconds":600,"replicas":2,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"currency-exchange"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"currency-exchange"}},"spec":{"containers":[{"image":"ezazulhaq02/currency-exchnage-service:0.0.2-SNAPSHOT","imagePullPolicy":"IfNotPresent","name":"currency-exchnage-service","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2021-08-25T17:46:23Z","lastUpdateTime":"2021-08-25T17:46:23Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2021-08-25T17:46:03Z","lastUpdateTime":"2021-08-25T17:46:23Z","message":"ReplicaSet \"currency-exchange-86758cd5cb\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":1,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
      creationTimestamp: "2021-08-25T17:46:03Z"
      generation: 2
      labels:
        app: currency-exchange
      name: currency-exchange
      namespace: default
      resourceVersion: "9048"
      uid: e697957c-3664-49db-92a3-81c85625c045
    spec:
      progressDeadlineSeconds: 600
      replicas: 2
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          app: currency-exchange
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: currency-exchange
        spec:
          containers:
            - image: ezazulhaq02/currency-exchnage-service:0.0.2-SNAPSHOT
              imagePullPolicy: IfNotPresent
              name: currency-exchnage-service
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
    status:
      availableReplicas: 2
      conditions:
        - lastTransitionTime: "2021-08-25T17:46:03Z"
          lastUpdateTime: "2021-08-25T17:46:23Z"
          message: ReplicaSet "currency-exchange-86758cd5cb" has successfully progressed.
          reason: NewReplicaSetAvailable
          status: "True"
          type: Progressing
        - lastTransitionTime: "2021-08-25T17:55:29Z"
          lastUpdateTime: "2021-08-25T17:55:29Z"
          message: Deployment has minimum availability.
          reason: MinimumReplicasAvailable
          status: "True"
          type: Available
      observedGeneration: 2
      readyReplicas: 2
      replicas: 2
      updatedReplicas: 2
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
