apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: currency-conversion
  name: currency-conversion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: currency-conversion
  template:
    metadata:
      labels:
        app: currency-conversion
    spec:
      containers:
        - image: ezazulhaq02/currency-conversion-service:0.0.2-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: currency-conversion-service
          resources:
            limits:
              memory: "128m"
              cpu: "500m"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: currency-conversion
  name: currency-conversion
spec:
  ports:
    - port: 8101
      protocol: TCP
      targetPort: 8101
  selector:
    app: currency-conversion
  type: LoadBalancer
