version: '3.7'

services: 
    currency-conversion:
        image: ezazulhaq02/currency-conversion-service:0.0.1-SNAPSHOT
        ports: 
            - 8101:8101
        networks: 
            - currency-network

networks: 
    currency-network: